// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBASv6JcO5Gu8q5_-O9-_P8Jr-kmBVYiCI',
    appId: '1:1053126543711:web:d7863bfcdfe7562f728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    authDomain: 'hunger-cbd8e.firebaseapp.com',
    storageBucket: 'hunger-cbd8e.appspot.com',
    measurementId: 'G-9QPQWFBNCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8sr0PbsNU4ZbtULPHz6hU9YMINAq2src',
    appId: '1:1053126543711:android:cbeb187330852a7b728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    storageBucket: 'hunger-cbd8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtpUB55QMjXwDYklTrjAz6eDH0PHLM0KQ',
    appId: '1:1053126543711:ios:1263f4aa0cf38da3728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    storageBucket: 'hunger-cbd8e.appspot.com',
    iosBundleId: 'com.example.hunger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtpUB55QMjXwDYklTrjAz6eDH0PHLM0KQ',
    appId: '1:1053126543711:ios:3ba6f160ea44d3c1728eea',
    messagingSenderId: '1053126543711',
    projectId: 'hunger-cbd8e',
    storageBucket: 'hunger-cbd8e.appspot.com',
    iosBundleId: 'com.example.hunger.RunnerTests',
  );
}
